### ISSUE TITLE
Crashes with another mod

### ISSUE THREAD

**Issue by gamusgoober** [ldtteam/vanilla-tools#10]
Crashes when using this mod:
https://www.curseforge.com/minecraft/mc-mods/super-tools

this may be caused by the name of the files which is easy. maybe, I have never coded.

**Comment by ravenbuilder934** [comment]
Yes, that's because internally this mod is called supertools. However, changing the internal name would remove all existing vanilla+ tools items when a user loaded up the new version with the name change. So this isn't really something we can fix. Maybe when 1.17 drops and there would be breaking changes anyway we can fix it

**Comment by ravenbuilder934** [comment]
Fixed in 1.17
